version: '3.6'
services:
  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_USER}
    volumes:
      - ./src/migrations:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
